version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: patient-management
    container_name: patient-management
    restart: unless-stopped
    working_dir: /patient-management
    volumes:
      - ./backend:/patient-management
    depends_on:
      - db
    networks:
      - laravel

  db:
    image: mysql:8.0
    container_name: laravel-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: patient_report
      MYSQL_ROOT_PASSWORD:
      MYSQL_USER: root
      MYSQL_PASSWORD:
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel
    ports:
      - "3306:3306"

  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/patient-management
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  dbdata:
